name: Build and push - All

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Base Image
      - name: Build and push node20
        uses: docker/build-push-action@v5
        with:
          context: ./node20/.
          push: true
          tags: labordigital/jest-puppeteer:node20
          platforms: linux/amd64,linux/arm64
          file: ./node20/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max